### ISSUE TITLE
[feature suggestion] add an option to display and quit

### ISSUE THREAD

**Issue by pcause** [aldrinzigmundv/zigfi#1]
Very nice tool.  Can you add an option to display the items for the specified list and quick.  Also, this wouldn't clear the screen.  Perhaps:

zigfi once <list, optional>

**Comment by aldrinzigmundv** [comment]
Thanks. Any reason why the current "show" command wouldn't do? Just asking. I think you want me to eliminate the Alternate Screen entirely for that command as well.

Also, you can update yours to v1.5.0, if you have downloaded the app already, and wanted an option to have the price difference (in percent) displayed for not just a day ago but a month and a year.

**Comment by pcause** [comment]
There are 2 uses cases:

- leave the app running and get regular updates on the price
- show current prices and perhaps pipe to other apps

My idea is that --once just writes each quote as a single text line to stdout and then exits.  no clear screen, and if stdout "isatty()" you output color otherwise not color escapes.

**Comment by aldrinzigmundv** [comment]
I'm working on just adding pipe capabilities to show if "isatty()", so we keep the number of commands to a minimum. I'll be adding JSON output capabilities as well, for the show command, where a "--json" flag is required. What do you think?

**Comment by aldrinzigmundv** [comment]
Added a new release with piping capabilities for `zigfi show`. Default output for pipe is string but `--json` flag can be added to get JSON instead. Please, check. Thanks.

**Comment by pcause** [comment]
downloaded the linux binary (tar.gz) and used on fedora.  Ran:

```bash
zigfi | more
```
and got this:
![image](https://user-images.githubusercontent.com/1071479/148763817-b4eca0ed-5509-4c32-b49a-fc6ea354ca2e.png)

When I ran "zigfi | cat" it dod the escape sequences to clear the screen and then display the list and exit.  Don't use the screen clearing stuff at all when piped output, just print directly.  

What I really wanted was just to have the lies directly output without the screen cleariing stuff or the repeated updated.  just get each quote and output to stdout.  Can be plan text or plan text with color escapes if output isatty

**Comment by aldrinzigmundv** [comment]
It's a bug when you don't give any arguments to `zigfi` at the moment and I'll have it fixed. I forgot to apply the feature to `zigfi` but if you use `zigfi show` with the name of the watchlist, it should work. Sorry and thanks for pointing it out.

**Comment by aldrinzigmundv** [comment]
I just fixed it. Please, check. Thanks.

I'm now working on the other open issue. 😊
