### ISSUE TITLE
[Suggestion] multiple change percentages

### ISSUE THREAD

**Issue by pcause** [aldrinzigmundv/zigfi#3]
If you changed the config file so an antry could be:

'^dj' : 1d:5d ,

the items after the ticker are intervals the user wants to see the percent change from today.  1d is the one day change, 5d is the t day change.  You can have a symbol for each one yahoo finance supprts

**Comment by aldrinzigmundv** [comment]
I don't get it. Are you suggesting a way for users to change the default interval for `zigfi show`?

Edit:
Oh, I think you meant per ticker, is that right?

**Comment by pcause** [comment]
yes, it would show

Yahoo $xx.43 Daychange% weekchange% ...

**Comment by aldrinzigmundv** [comment]
I was thinking of making it a default that, when piping, multiple percentages will come out from `stdout`, but that would be inconsistent with `zigfi show`'s current implementation where you have to provide an interval or you get the default `1d`. I don't think it's going to work at the moment until we're able to think of a way to implement it consistent with the current structure and in a simple way, if I understand you correctly.

**Comment by aldrinzigmundv** [comment]
Closing issue after not getting any response. Please, don't hesitate to open a new issue if you have any ideas on how to implement this feature better, or if you find new bugs or have new suggestions. Thanks.
